name: Terraform CI

on:
  push:
    branches: [main, oidc]  # Run fmt/validate/lint on push
  pull_request:
    branches: [main]         # Run terraform plan on PRs targeting main

permissions:
  id-token: write
  contents: read

jobs:
  lint-validate:
    name: Lint & Validate
    runs-on: ubuntu-latest
    if: github.event_name == 'push'  # Only run on push
    strategy:
      matrix:
        module:
          - vpc
          - ec2
          - s3-static-site
          - cloudfront
    defaults:
      run:
        shell: bash
        working-directory: modules/${{ matrix.module }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Install TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.50.3
      - name: TFLint Run
        run: tflint --init && tflint

  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'  # Only run on PRs
    strategy:
      matrix:
        module:
          #- vpc
          - ec2
          #- s3-static-site
          #- cloudfront
    defaults:
      run:
        shell: bash
        working-directory: modules/${{ matrix.module }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.GITHUBACTIONS_ROLE_ARN }}
          aws-region: eu-central-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Terraform Plan
        run: terraform plan
